### ISSUE TITLE
FEATURE: Be able to change the special characters in the parse.

### ISSUE THREAD

**Issue by jmverges** [TYPO3Fluid/Fluid#106]
Could be really nice if "{" and "}" could be set somehow somewhere depending of something. I'm sure I'm not the first one that thought about this while was working with .json templates. I know this is possible in other template systems, so could be good for us. Not sure how much effort is needed or if the parse process could decrease the performance a lot. By now I saw is "hardcoded" everywhere which looked strange for me so my only thought about this reason was performance. 

Any feedback is welcomed as always.

**Comment by helhum** [comment]
We should *not* do this imho. This would overload an essential syntax. It would be like having the option in PHP to change the `[]` to a different operator for writing arrays. We will run in all sorts of issues, when doing so.

**Comment by helhum** [comment]
> I know this is possible in other template systems

Can you point out some examples?

> Using format.raw is a bit painfull.

how does format.raw come into play here?

**Comment by jmverges** [comment]
http://www.smarty.net/forums/viewtopic.php?t=18276&sid=3927728a9b0fb0cdfcee2b71a3d9b7ae

Index.json:

`[
    <f:for each="{groups}" as="group" iteration="i">
      <f:format.raw>{</f:format.raw>"{group.id}" : "{group.name}"<f:format.raw>}</f:format.raw><f:if condition="{i.isLast}"><f:else>,</f:else></f:if>
    </f:for>
]`

Please, I wouldn't like to start to assess if Smarty is good or bad neither if the example code I wrote makes sense at all. 

Thanks in advance.

**Comment by mneuhaus** [comment]
To be honest, i'd recommend something likehttps://github.com/thephpleague/fractal to create json. Using a template engine to render a structured data Format isn't something i'd do in a tenplate engine, because its more trouble/overhead than really useful. :-)

**Comment by jmverges** [comment]
Well, I imagine a "world" where each component could be rendered in different ways. If I'm using f:format.currency or whatever in an html template and I'm changing from html response to json response depending on the request type why should I look for other way than using f:format.currency for my json template response? (just a dumb example) I should then split the controller, define which variables should be transformed in php,  for each use case, change routes, and implement a different action for same component. Fluid can provide me all what I need, couldn't it?

**Comment by NamelessCoder** [comment]
I lean towards not making these dynamic, but there could also be a bug (technically speaking... not even sure I'd call it a bug). I'll try to explain what I think is going on, with a bit of background:

#### Array and JSON syntax confusion

Historically Fluid used to parse templates in a way that would detect array syntax - `{key: value}` - also *outside* ViewHelper arguments. This was later changed so it only detects this syntax *inside* ViewHelper arguments - and that changed helped a lot. After this was done, template devs experienced a lot fewer of the `Array` string outputs when writing Fluid with JSON. And there was much rejoicing (and no pain whatsoever that I'm aware of).

#### Enter recursive variable extraction and ExpressionNodes

Now, however, the expression that matches things inside curly braces is much broader - in two ways. First, it enables custom ExpressionNodes (this type of integration always triggers on things inside curly braces). Second, Fluid enables recursive object accessors which, depending on the exact syntax that you use to write JSON, may cause the JSON array to be seen as a *variable reference containing dynamic parts*.

Both of those could cause the JSON output to become unexpected. And both cases are solvable as @jmverges by using `<f:format.raw>` to escape one of the sides of all curly brace enclosures. Which I agree is less than ideal, but is a long known restriction of Fluid + JSON (also in earlier versions and also on Flow).

#### So why not allow substituting the markers?

I would give a couple of reasons not related to performance (since performance can nearly always be "good enough" by using constants etc. for such things). The more important reasons would be:

* Replacing the marker puts requirements on everything that until this point has been integrating with any feature that can be trusted to deliver `{}` (for example, ExpressionNodes would have to become much more complex and creators of those would be required to use new constants, always).
* Fluid can render recursively and switch formats in between. You can for example do `<f:render partial="MyJsonObjects.json" section="myObject" variables="{foo: bar}" />` from any HTML or XML template and the output will be JSON. But you'd not be able to designate the delimiters there; at least not without introducing yet another set of context manipulating arguments for `f:render` which I'd object to doing - and it would not be responsible of us to forcibly replace the delimiters based on format.

There are other reasons which all stem from those two reasons above; the main bulk of reasons concern the large amounts of API changes we would have to introduce in many places and the very negative effects it would have if we try to introduce this *by convention*, e.g. enforcing a new bracket syntax based on format of template.

Hopefully this explains enough of my objection to this. In and of itself it's not a bad suggestion but the deeper you dig the more complicated it becomes to introduce something like that (and the more complex the Fluid API becomes due to the many ways we would have to enable for defining these). I would agree with the "Fluid is not ideal for JSON" conclusion and add that you might consider a custom VH that uses another engine, or wrapping everything you want to protect with CDATA; rather than `f:format.raw` which I agree can be cumbersome.

**Comment by NamelessCoder** [comment]
Will take the liberty of closing this one with reference to the two root reasons given above. That doesn't mean we give up on making the described use case a better experience - but replacing the delimiters is not the way to do it. The feature request is sensible enough but unfortunately also highly impractical to implement due to how Fluid works internally.
