### ISSUE TITLE
Boolean ViewHelper arguments containing "false" are considered FALSE

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3Fluid/Fluid#6]
```html
<f:if condition="anArbitary String containing FaLsE">
  <f:then>then</f:then>
  <f:else>else</f:else>
</f:if>
```
## Expected output

```
then
```

## Actual output

```
else
```

Also:
```html
<f:if condition="   FALSE   ">
  <f:then>then</f:then>
  <f:else>else</f:else>
</f:if>
```
## Expected output

```
then
````

## Actual output

```
else
```

**Comment by NamelessCoder** [comment]
Interesting! The trimmed-to-`FALSE` case makes sense (imho this whitespace-surrounded condition is an edge case; we could support it with an added check) but the other one is quite strange, having any casing of `false` anywhere in the string... broken regular expression?

**Comment by NamelessCoder** [comment]
Hang on a second here. This syntax will never, ever happen - not even with an unrolled ObjectAccessorNode returning a string that is then fed to the BooleanNode (e.g. `<f:if condition="{variableContainingStringContainingFalse}" then="yes" else="no" />` still correctly returns "yes".

Correctly quoting the hardcoded string has a completely different and correct result. Un-quoted strings *are intended to be parsed as possible expression parts separated by whitespace* so your node actually results in this stack:

```php
$parts = array('anArbitary', 'String', 'containing', 'FaLsE');
```

...which would be fine if each of those words instead were a number, a comparator, a Fluid variable reference etc.

I've added some new test cases in the linked commit which test for the proper syntax variation of this first reported issue and they return TRUE as they should. However: the current string trimming behavior is indeed unpredictable; it would forcibly trim both quotes **and** any whitespace in the string that was quoted, whether or not the string came from a hardcoded TextNode or an ObjectAccessorNode. The linked patch fixes that situation by first checking if an encountered string is quoted and if it is, carefully trimming only quotes from it. It is done by trimming only the first character of the string so that any nested quotes like `'"nested"'` becomes `"nested"` rather than `nested`. In addition, the constructor of BooleanNode is made responsible for the initial trimming of the expression when the expression is a plain old string (meaning it comes hardcoded from Fluid template).

**Comment by bwaidelich** [comment]
Hi,

> Hang on a second here. This syntax will never, ever happen

But doesn't this example proof the opposite: http://134.119.11.221/flowpack.viewhelpertest/standard/index?selectedPartial=if ?

**Comment by NamelessCoder** [comment]
Hi Bastian - are you working on that installation currently? It gives me a well-known type error maybe caused by missing aliases.

**Comment by bwaidelich** [comment]
hm no, I just updated the typo3fluid/fluid package.. let me check

**Comment by bwaidelich** [comment]
I finally managed to update & fix the test server and the issue still exists: http://134.119.11.221/flowpack.viewhelpertest/standard/index?selectedPartial=if

The reasons for the two failing tests are actually different:
string values are always trimmed, so that `"  FALSE  "` is actually the same as `"FALSE"` and I think that we can definitely live with that.

The other one actually is not related to the string containing "false" but the new parser splits all strings at word boundaries, so
```
<f:if condition="some arbitrary string">
```

will always evaluate to FALSE..

I think that's something we need to fix or communicate very clearly

**Comment by mneuhaus** [comment]
This has been fixed through the Boolean descent parser: 
https://github.com/TYPO3Fluid/Fluid/commit/7f4240e2a77502c551a4354fde9607564fcd1af0#diff-6339dd4d35c24456665f3d1f84e8d0e5R22
